src/Entity/Bookmark.php
<?php

namespace App\Entity;

use App\Repository\BookmarkRepository;
use App\Validator\UniqueUrl;
use App\Validator\Url;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @ORM\Entity(repositoryClass=BookmarkRepository::class)
 */
class Bookmark
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     * @NotBlank(message="Url-адрес не должен быть пустым")
     * @Url()
     * @UniqueUrl()
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $page_title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $favicon;

    /**
     * @ORM\ManyToMany(targetEntity=Keyword::class, inversedBy="bookmarks")
     */
    private $keywords;

    public function __construct()
    {
        $this->keywords = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getPageTitle(): ?string
    {
        return $this->page_title;
    }

    public function setPageTitle(string $page_title): self
    {
        $this->page_title = $page_title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFavicon(): ?string
    {
        return $this->favicon;
    }

    public function getFaviconPath() {
        return "images/favicons/{$this->getFavicon()}";
    }

    public function setFavicon(string $favicon): self
    {
        $this->favicon = $favicon;

        return $this;
    }

    /**
     * @return Collection|Keyword[]
     */
    public function getKeywords(): Collection
    {
        return $this->keywords;
    }

    public function addKeyword(Keyword $keyword): self
    {
        if (!$this->keywords->contains($keyword)) {
            $this->keywords[] = $keyword;
        }

        return $this;
    }

    public function removeKeyword(Keyword $keyword): self
    {
        $this->keywords->removeElement($keyword);

        return $this;
    }
}

src/Controller/BookmarksController.php
<?php

namespace App\Controller;

use App\Entity\Bookmark;
use App\Entity\Keyword;
use App\Form\BookmarkFormType;
use App\Repository\BookmarkRepository;
use App\Service\PageLoader\Exception\LoaderException;
use App\Service\PageLoader\FaviconHandler;
use App\Service\PageLoader\LoaderInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Faker\Factory;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookmarksController extends AbstractController
{
    /**
     * @param Request            $request
     * @param BookmarkRepository $bookmarkRepository
     * @param PaginatorInterface $paginator
     *
     * @Route("/", name="app_bookmarks")
     *
     * @return Response
     */
    public function index(
        Request $request,
        BookmarkRepository $bookmarkRepository,
        PaginatorInterface $paginator
    ): Response {
        $pagination = $paginator->paginate(
            $bookmarkRepository->findAllQuery(),
            $request->query->getInt('page', 1),
            20
        );
        return $this->render('bookmarks/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    /**
     * @param BookmarkRepository $bookmarkRepository
     * @param int                $id
     *
     * @Route("/bookmarks/{id}", name="app_bookmarks_detail")
     *
     * @return Response
     * @throws NonUniqueResultException
     */
    public function detail(BookmarkRepository $bookmarkRepository, int $id): Response
    {
        $bookmark = $bookmarkRepository->findByIdWithKeywords($id);

        if (!$bookmark) {
            throw $this->createNotFoundException("Not found bookmark with id {$id}");
        }

        return $this->render('bookmarks/detail.html.twig', [
            'bookmark' => $bookmark,
        ]);
    }

    /**
     * @param Request                $request
     * @param EntityManagerInterface $entityManager
     * @param LoaderInterface        $loader
     *
     * @Route("/add", name="app_bookmarks_add")
     *
     * @return Response
     */
    public function add(Request $request, EntityManagerInterface $entityManager, LoaderInterface $loader): Response {
        $form = $this->createForm(BookmarkFormType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Bookmark $bookmark */
            $bookmark = $form->getData();

            try {
                $response = $loader->download($bookmark->getUrl());
            } catch (LoaderException $e) {
                $this->addFlash(
                    'flash_message',
                    'Не удалось получить данные по закладке. Проверьте работоспособность сайта по указанному url'
                );

                return $this->render('bookmarks/add.html.twig', [
                    'bookmarkForm' => $form->createView()
                ]);
            }

            $favicon = $response->getFavicon();

            (new FaviconHandler(new Filesystem(), $favicon))->save();

            $bookmark
                ->setFavicon($response->getFavicon()->getName())
                ->setPageTitle($response->getTitle())
                ->setDescription($response->getDescription());

            foreach ($response->getKeywords() as $keyword) {
                $keywordEntity = new Keyword();
                $keywordEntity->setName($keyword);

                $entityManager->persist($keywordEntity);

                $bookmark->addKeyword($keywordEntity);
            }

            $entityManager->persist($bookmark);
            $entityManager->flush();

            $this->addFlash('flash_message', 'Закладка успешно создана!');

            return $this->redirectToRoute('app_bookmarks_detail', ['id' => $bookmark->getId()]);
        }

        return $this->render('bookmarks/add.html.twig', [
            'bookmarkForm' => $form->createView()
        ]);
    }
}

templates/bookmarks/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавление новой закладки{% endblock %}

{% block content %}
    <h1>Добавление новой закладки</h1>

    {{ form_start(bookmarkForm) }}
        {{ form_widget(bookmarkForm) }}
        <button type="submit" class="btn btn-primary">Отправить</button>
    {{ form_end(bookmarkForm) }}
{% endblock %}

templates/bookmarks/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Детальный просмотр закладки{% endblock %}

{% block content %}
    <h1>Детальный просмотр закладки</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Заголовок страницы</th>
                <th>Favicon</th>
                <th>Url страницы</th>
                <th>META Description</th>
                <th>META Keywords ({{ bookmark.keywords|length }})</th>
                <th>Дата добавления</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ bookmark.pageTitle }}</td>
                <td>
                    <img src="{{ asset(bookmark.faviconPath) }}">
                </td>
                <td>{{ bookmark.url }}</td>
                <td>{{ bookmark.description }}</td>
                <td>
                    {% for keyword in bookmark.keywords %}
                        <span>{{ keyword.name }}</span><br><br>
                    {% endfor %}
                </td>
                <td>{{ bookmark.createdAt|date("d.m.Y H:i:s") }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/bookmarks/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Управление закладками{% endblock %}

{% block content %}
    <h1>Управление всеми закладками ({{ pagination.totalItemCount }})</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Заголовок страницы</th>
                <th>Favicon</th>
                <th>Url страницы</th>
                <th>Дата добавления</th>
            </tr>
        </thead>
        <tbody>
            {% for bookmark in pagination %}
                <tr>
                    <td>
                        <a href="{{ path('app_bookmarks_detail', {id: bookmark.id}) }}">{{ bookmark.pageTitle }}</a>
                    </td>
                    <td>
                        <img src="{{ asset(bookmark.faviconPath) }}">
                    </td>
                    <td>{{ bookmark.url }}</td>
                    <td>{{ bookmark.createdAt|date("d.m.Y H:i:s") }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ knp_pagination_render(pagination) }}
{% endblock %}